name: flutter_app1
description: "A Mood Diary app built with Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/data/quotes.json
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.2
  table_calendar: ^3.1.1
  intl: ^0.19.0
  flutter_markdown: ^0.7.1
  uuid: ^4.3.3
  
  # === 移除 Isar, 改用 ObjectBox ===
  objectbox: ^2.4.0
  objectbox_flutter_libs: ^2.4.0 # 這會自動處理 Android 依賴，不用改 Gradle
  
  fl_chart: ^0.68.0
  flame: 1.18.0           # 強制鎖定
  flame_forge2d: 0.18.0   # 強制鎖定

 # 相機與相簿
  image_picker: ^1.0.7
  path: ^1.9.0  # 用來處理副檔名

  # share 功能
  screenshot: ^3.0.0   # 用來截圖
  share_plus: ^10.1.2  # 用來呼叫系統分享

  # 遠端雞湯
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  google_generative_ai: ^0.4.0

  # 壓縮與解壓縮 + 檔案選取 +備份還原
  archive: ^3.6.1
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  
  # === 改用 ObjectBox Generator ===
  objectbox_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher" # Android 的 icon 檔案名稱
  ios: true              # 自動產生 iOS icon
  image_path: "assets/icon.png" # 你的圖片路徑 (要跟步驟一的路徑一樣)
  min_sdk_android: 21    # 建議加上
  remove_alpha_ios: true # iOS icon 不支援透明背景，這會自動幫你填滿背景色 (通常是黑色或白色，若有透明背景建議自己先處理好)